### ISSUE TITLE
How do you actually run this

### ISSUE THREAD

**Issue by UltimateBoi** [zemlyak/hypixel-bot#7]

**Comment by zemlyak** [comment]
It's a VKontakte (russian social network) bot.

To run it you need to either use the dockerfile or compile it using go build.
When starting the bot you need to have VK_TOKEN and HYPIXEL_KEY set to your group's vk token and hypixel api key.
Also some features require a sqlite database, the schema is in the dockerfile.

**Comment by UltimateBoi** [comment]
ok thanks

**Comment by tnkv** [comment]
нуок
